### ISSUE TITLE
should support trusted timestamping

### ISSUE THREAD

**Issue by karchie** [ritschwumm/xsbt-webstart#6]
using -tsa argument to jarsigner

**Comment by ritschwumm** [comment]
that's just some arbitrary url passed after -tsa, right?

**Comment by ritschwumm** [comment]
hm. jarsigner seems to have a lot of options nowadays. adding just a single new field to KeyConfig looks like not even half a solution. any ideas for something better?

**Comment by karchie** [comment]
good point; I will think about it but I'm new to scala so don't trust my design sense yet

**Comment by ritschwumm** [comment]
the jnlp descriptor originally was a case class, just like KeyConfig is now. at some stage i stopped trying to implement each and every feature and just let the user pass an xml Node...

**Comment by ritschwumm** [comment]
probably outdated now
