### ISSUE TITLE
Delete the jar if sign or verification fail

### ISSUE THREAD

**Issue by nigredo-tori** [ritschwumm/xsbt-webstart#9]
Currently the jars are signed in-place in `webstartBuildDir`. If we get an error, the `webstart` task fails, but the jar itself remains in `webstartBuildDir`, unsigned. On the next `webstart` launch it is considered signed, and can get into the resulting artifact.

A simple solution for this would be to either remove the jar if sign or verification fail, or to sign and verify it in a temporary file, and only copy the result to `webstartBuildDir` once we know it is valid.

**Comment by ritschwumm** [comment]
nice catch!

**Comment by ritschwumm** [comment]
will be fixed in the next release
